### ISSUE TITLE
Cannot D&D or copy from HDFS to local

### ISSUE THREAD

**Issue by kadaan** [trol73/mucommander#104]
When I try to D&D or copy from HDFS to local I get the following errors:

```
2016-03-18 08:02:18.015 JavaAppLauncher[94410:20724900] __CFPasteboardIssueSandboxExtensionForPath : sandbox extension creation failed: caller requested extension for path that could not be resolved to an absolute path: [/Users/USERNAME/hdfs:/SERVER:9000/user/yarn/GobblinYarn/application_1457131141434_0056/container/_appfiles/reference.conf]
2016-03-18 08:02:18.016 JavaAppLauncher[94410:20724876] __CFPasteboardIssueSandboxExtensionForPath : sandbox extension creation failed: caller requested extension for path that could not be resolved to an absolute path: [/Users/USER/hdfs:/SERVER:9000/user/yarn/GobblinYarn/application_1457131141434_0056/container/_appfiles/reference.conf]
2016-03-18 08:02:18.017 JavaAppLauncher[94410:20724876] __CFPasteboardCreateSandboxExtensionDataFromCFData : failed to obtain sandbox extension data for url [file://localhost/Users/USER/hdfs:/SERVER:9000/user/yarn/GobblinYarn/application_1457131141434_0056/container/_appfiles/reference.conf]
2016-03-18 08:02:19.008 JavaAppLauncher[94410:20724848] Failed to obtain a valid sandbox extension for item: [789514] of flavor: [dyn.ah62d4rv4gu8y6y4grf0gn5xbrzw1gydcr7u1e3cytf2gn] from the pasteboard.  Because the sandbox extension was still being set.
2016-03-18 08:02:19.008 JavaAppLauncher[94410:20724848] Failed to get a sandbox extensions for itemIdentifier (789514).  The data for the sandbox extension was still proxy data
2016-03-18 08:02:19.008 JavaAppLauncher[94410:20724848] Failed to obtain a valid sandbox extension for item: [789514] of flavor: [dyn.ah62d4rv4gu8y6y4grf0gn5xbrzw1gydcr7u1e3cytf2gn] from the pasteboard.  Because the sandbox extension was still being set.
2016-03-18 08:02:19.008 JavaAppLauncher[94410:20724848] Failed to get a sandbox extensions for itemIdentifier (789514).  The data for the sandbox extension was still proxy data
2016-03-18 08:02:19.011 JavaAppLauncher[94410:20724848] No valid sandbox extension for item: [789514] of flavor: [public.file-url] was created.
2016-03-18 08:02:19.011 JavaAppLauncher[94410:20724848] Failed to get a sandbox extensions for itemIdentifier (789514).  The data for the sandbox extension was NULL
2016-03-18 08:02:19.011 JavaAppLauncher[94410:20724848] No valid sandbox extension for item: [789514] of flavor: [public.file-url] was created.
2016-03-18 08:02:19.011 JavaAppLauncher[94410:20724848] Failed to get a sandbox extensions for itemIdentifier (789514).  The data for the sandbox extension was NULL
destFileName reference.conf
destFile /Users/USER/Downloads/reference.conf
Sticky cursor!
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException
    at com.mucommander.ui.main.table.FileTable.changeSelection(FileTable.java:1441)
    at javax.swing.plaf.basic.BasicTableUI$Handler.mouseDragged(BasicTableUI.java:1253)
    at javax.swing.plaf.basic.BasicTableUI$MouseInputHandler.mouseDragged(BasicTableUI.java:818)
    at java.awt.AWTEventMulticaster.mouseDragged(AWTEventMulticaster.java:319)
    at java.awt.AWTEventMulticaster.mouseDragged(AWTEventMulticaster.java:319)
    at java.awt.AWTEventMulticaster.mouseDragged(AWTEventMulticaster.java:319)
    at java.awt.Component.processMouseMotionEvent(Component.java:6583)
    at javax.swing.JComponent.superProcessMouseMotionEvent(JComponent.java:3348)
    at javax.swing.Autoscroller.actionPerformed(Autoscroller.java:176)
    at javax.swing.Timer.fireActionPerformed(Timer.java:313)
    at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
    at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
    at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
    at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
    at java.awt.Dialog.show(Dialog.java:1084)
    at java.awt.Component.show(Component.java:1673)
    at java.awt.Component.setVisible(Component.java:1625)
    at java.awt.Window.setVisible(Window.java:1014)
    at java.awt.Dialog.setVisible(Dialog.java:1005)
    at com.mucommander.ui.dialog.FocusDialog.showDialog(FocusDialog.java:270)
    at com.mucommander.ui.dialog.file.ProgressDialog.start(ProgressDialog.java:287)
    at com.mucommander.ui.dnd.FileDropTargetListener.drop(FileDropTargetListener.java:289)
    at java.awt.dnd.DropTarget.drop(DropTarget.java:455)
    at sun.awt.dnd.SunDropTargetContextPeer.processDropMessage(SunDropTargetContextPeer.java:538)
    at sun.lwawt.macosx.CDropTargetContextPeer.processDropMessage(CDropTargetContextPeer.java:143)
    at sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchDropEvent(SunDropTargetContextPeer.java:852)
    at sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchEvent(SunDropTargetContextPeer.java:776)
    at sun.awt.dnd.SunDropTargetEvent.dispatch(SunDropTargetEvent.java:48)
    at java.awt.Component.dispatchEventImpl(Component.java:4746)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    at java.awt.LightweightDispatcher.processDropTargetEvent(Container.java:4599)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4461)
    at java.awt.Container.dispatchEventImpl(Container.java:2280)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by papandreus1** [comment]
Do you mean Hadoop Distributed File System as HDFS?

**Comment by kadaan** [comment]
Yes
