### ISSUE TITLE
Can't connect to any smb://

### ISSUE THREAD

**Issue by DenimTornado** [trol73/mucommander#147]
I try to connect to several smb servers, on different OS with credentials and without. No suucess. I only get "Connecting to folder, press Escape to cancel". 

I use MacOS version of trolCommander v0.9.9.

**Comment by trol73** [comment]
Could you run trolcommander.jar from the terminal with command
`java -jar trolcommander.jar`
and show the output?

**Comment by DenimTornado** [comment]
Exception in thread "Thread-8" java.lang.ClassFormatError: Invalid pc in LineNumberTable in class file jcifs/smb/SmbFile
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.mucommander.commons.file.impl.smb.SMBFile.createSmbFile(SMBFile.java:137)
	at com.mucommander.commons.file.impl.smb.SMBFile.<init>(SMBFile.java:70)
	at com.mucommander.commons.file.impl.smb.SMBFile.<init>(SMBFile.java:58)
	at com.mucommander.commons.file.impl.smb.SMBProtocolProvider.getFile(SMBProtocolProvider.java:92)
	at com.mucommander.commons.file.FileFactory.createRawFile(FileFactory.java:604)
	at com.mucommander.commons.file.FileFactory.getFile(FileFactory.java:560)
	at com.mucommander.commons.file.FileFactory.getFile(FileFactory.java:457)
	at com.mucommander.commons.file.FileFactory.getFile(FileFactory.java:436)
	at com.mucommander.core.LocationChanger$ChangeFolderThread.run(LocationChanger.java:676)

**Comment by DenimTornado** [comment]
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

**Comment by DenimTornado** [comment]
Any news?

**Comment by trol73** [comment]
I have fixed it just now. Please, check the "nightly" build

**Comment by DenimTornado** [comment]
Yes! Works like a charm. Thank you very mush!
