### ISSUE TITLE
Does not start in macOS 10.13.4

### ISSUE THREAD

**Issue by Magneticdud** [trol73/mucommander#163]
Does not start in macOS 10.13.4

It loads the start screen, then disappears

The only thing i find in logs is:

> JavaAppLauncher: AEGetDescData of non-desc type 'reco' not a good idea

my java:

> java -version
> java version "1.8.0_131"
> Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
> Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

**Comment by Magneticdud** [comment]
If i run it with 

`java -jar /Applications/trolCommander.app/Contents/Java/trolcommander.jar `

works fine (but ugly java icon)

**Comment by trol73** [comment]
Can't reproduce this issue. I use trolCommander in MacOS 10.13.4

**Comment by Magneticdud** [comment]
The control panel shows a never heard before Java 10.0.1 which maybe it got an automatic update recently

![schermata 2018-05-04 alle 11 15 50](https://user-images.githubusercontent.com/2940598/39620776-90194780-4f8c-11e8-8b9d-eed4ead41d53.png)

The terminal shows the right java though

```
/usr/libexec/java_home -V
Matching Java Virtual Machines (3):
    1.8.0_131, x86_64:	"Java SE 8"	/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home
    1.6.0_65-b14-468, x86_64:	"Java SE 6"	/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
    1.6.0_65-b14-468, i386:	"Java SE 6"	/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
```

**Comment by Magneticdud** [comment]
I tried to launch the JavaAppLauncher in Contents/MacOS , and I get more details on the crash:

```
./JavaAppLauncher 
16:08:30,028 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
16:08:30,029 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/Applications/trolCommander.app/Contents/Java/trolcommander.jar!/logback.xml]
16:08:30,234 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
16:08:30,261 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
16:08:30,264 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [CONSOLE_APPENDER]
16:08:30,383 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
16:08:30,383 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Pushing component [encoder] on top of the object stack.
16:08:30,485 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
16:08:30,486 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [DEV_APPENDER]
16:08:30,494 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
16:08:30,494 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Pushing component [encoder] on top of the object stack.
16:08:30,496 |-WARN in ch.qos.logback.core.rolling.RollingFileAppender[DEV_APPENDER] - No TriggeringPolicy was set for the RollingFileAppender named DEV_APPENDER
16:08:30,496 |-WARN in ch.qos.logback.core.rolling.RollingFileAppender[DEV_APPENDER] - For more information, please visit http://logback.qos.ch/codes.html#rfa_no_tp
16:08:30,496 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
16:08:30,496 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [CONSOLE_APPENDER] to Logger[ROOT]
16:08:30,500 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [DEV_APPENDER] to Logger[ROOT]
16:08:30,500 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [ch.qos.logback] to WARN
16:08:30,500 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [ch.qos.logback] to true
16:08:30,500 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.mucommander] to INFO
16:08:30,500 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [com.mucommander] to true

 500  INFO [main             ] - Current OS family: Mac OS X                                                                                                                                                                              - 2018-05-08 16:08:30,507 com.mucommander.TrolCommander (TrolCommander.java:779)
Processors: 4
No value for extension in language null, using English value
No value for name in language null, using English value
No value for size in language null, using English value
No value for date in language null, using English value
No value for permissions in language null, using English value
No value for owner in language null, using English value
No value for group in language null, using English value
[2018-05-08 16:08:31.051] WARNING LauncherCmdHelper.java#printError,326 Could not load custom commands: /Users/user/Library/Preferences/trolCommander/commands.xml (No such file or directory). Using default values.
[2018-05-08 16:08:31.053] WARNING LauncherCmdHelper.java#printError,326 Could not load custom associations: /Users/user/Library/Preferences/trolCommander/associations.xml (No such file or directory). Using default values.
finished
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by ru.trolsoft.macosx.RetinaImageIcon (file:/Applications/trolCommander.app/Contents/Java/trolcommander.jar) to field sun.awt.CGraphicsDevice.scale
WARNING: Please consider reporting this to the maintainers of ru.trolsoft.macosx.RetinaImageIcon
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
java.lang.NoClassDefFoundError: com/sun/java/swing/plaf/windows/WindowsLookAndFeel
	at com.jidesoft.plaf.LookAndFeelFactory.installJideExtension(Unknown Source)
	at com.jidesoft.plaf.LookAndFeelFactory.installJideExtension(Unknown Source)
	at com.jidesoft.plaf.LookAndFeelFactory.installJideExtension(Unknown Source)
	at com.jidesoft.swing.StyledLabel.updateUI(Unknown Source)
	at java.desktop/javax.swing.JLabel.<init>(Unknown Source)
	at java.desktop/javax.swing.JLabel.<init>(Unknown Source)
	at com.jidesoft.swing.StyledLabel.<init>(Unknown Source)
	at com.jidesoft.swing.StyledLabelBuilder.createStyledLabel(Unknown Source)
	at com.mucommander.ui.main.table.FileTable$2.createRefreshNonExistingLocationLabel(FileTable.java:334)
	at com.mucommander.ui.main.table.FileTable$2.<init>(FileTable.java:330)
	at com.mucommander.ui.main.table.FileTable.createOverlayableTable(FileTable.java:326)
	at com.mucommander.ui.main.table.FileTable.<init>(FileTable.java:244)
	at com.mucommander.ui.main.FolderPanel.<init>(FolderPanel.java:183)
	at com.mucommander.ui.main.MainFrame.<init>(MainFrame.java:289)
	at com.mucommander.ui.main.frame.DefaultMainFramesBuilder.createMainFrame(DefaultMainFramesBuilder.java:112)
	at com.mucommander.ui.main.frame.DefaultMainFramesBuilder.build(DefaultMainFramesBuilder.java:80)
	at com.mucommander.ui.main.WindowManager.createNewMainFrame(WindowManager.java:172)
	at com.mucommander.TrolCommander$CreateWindowTask.run(TrolCommander.java:358)
	at com.mucommander.TrolCommander$LauncherTask.call(TrolCommander.java:182)
	at com.mucommander.TrolCommander$LauncherTask.call(TrolCommander.java:158)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.sun.java.swing.plaf.windows.WindowsLookAndFeel
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 24 more
[2018-05-08 16:08:33.443] WARNING LauncherCmdHelper.java#printError,326 Launcher getTask error for launcher.window: : com/sun/java/swing/plaf/windows/WindowsLookAndFeel. Using default values.
java.io.IOException: Not Found
	at com.mucommander.commons.file.impl.http.HTTPFile.checkHTTPResponse(HTTPFile.java:251)
	at com.mucommander.commons.file.impl.http.HTTPFile.getInputStream(HTTPFile.java:405)
	at com.mucommander.VersionChecker.getInstance(VersionChecker.java:139)
	at com.mucommander.TrolCommander.lambda$main$0(TrolCommander.java:940)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue.access$600(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by trol73** [comment]
It seems that you are using Java 9 or 10

**Comment by Magneticdud** [comment]
but it works fine if i launch it with java -jar "path to the jar"

looks like the automatic updater f***ing installed a java version that i even did not know it existed (java 10? wasn't it at 8?)

**Comment by trol73** [comment]
Usually the automatic updater doesn't download the other major version of java itself..

**Comment by Magneticdud** [comment]
I managed to downgrade to 171. If i run java -version it shows version 131. Well the important is now it works. F*** Oracle and their beta quality software
